@startuml Test UML Class
package pkg/conf {
	package conf {
		class Conf {
			CnfPath string
			ProjectName string
			ProjectRoot string
			ExcludeDirs []string
			OutDir string
			ClassF string
			ActF string
		}
	}
}
package pkg/dir {
	package mapf {
	}
	package readf {
	}
}
package pkg/errd {
	package errd {
		class ErrMeta {
			Caller string
		}
		class ConfDecodeError {
			Path string
			Err error
		}
		class FileCreateError {
			Path string
			Err error
		}
		class FileWriteError {
			Path string
			Err error
		}
		class FileOpenError {
			Path string
			Err error
		}
		class FileReadError {
			Path string
			Err error
		}
		class FileRecursionError {
			Path string
			Ftyp string
			Err error
		}
		class FileAbsError {
			Path string
			Err error
		}
		class JSONEncodeError {
			FName string
			Err error
		}
		class WriterError {
			WriterLoc string
			NumBytes int
			Err error
		}
	}
}
package pkg/puml {
	package puml {
		class Puml {
			Dgm PumlWriter
		}
		class UmlClass {
			Title string
			r *rgx.Rgx
		}
		class UmlActivity {
			Title string
		}
	}
}
package pkg/rgx {
	package rgx {
		class Rgx {
			ready RgxReady
			PkgMap RgxPkgMap
			Funcs []*RgxFunc
			Structs []*RgxStruct
		}
		class RgxFile {
			Pkg string
			Name string
			Funcs []*RgxFunc
			Structs []*RgxStruct
		}
		class RgxMatch {
			FindType string
			MatchStr string
			Groups []string
		}
		class RgxFunc {
			Name string
			Params string
			Rtn string
			IsMthd bool
			BelongsTo string
		}
		class RgxStruct {
			Name string
			Fields []RgxStructFld
		}
		class RgxStructFld {
			Name string
			DType string
			Cmnt string
			Tag string
		}
	}
}
package pkg/str {
	package str {
	}
}
package cli {
	package cli {
		class Args {
			Init bool
		}
	}
}
package main {
	package main {
	}
}

@enduml