@startuml Test UML Class
package main {
	package main {
	}
}
package pkg/conf {
	package conf {
		class Conf {
			CnfPath string
			ProjectName string
			ProjectRoot string
			ExcludeDirs []string
			OutDir string
			ClassF string
			ActF string
		}
	}
}
package pkg/dir {
	package mapf {
	}
	package readf {
	}
}
package pkg/errd {
	package errd {
		class WriterError {
			WriterLoc string
			NumBytes int
			Err error
		}
	}
}
package pkg/puml {
	package puml {
		class UmlActivity {
			Title string
		}
	}
}
package pkg/rgx {
	package rgx {
		class RgxStructFld {
			Name string
			DType string
			Cmnt string
			Tag string
		}
	}
}
package pkg/str {
	package str {
	}
}
package cli {
	package cli {
		class Args {
			Init bool
		}
	}
}

@enduml