@startuml nba-etl | Class Diagram
package main {
	package args {
		class args_funcs {
			+ parseArgs() Args 
		}
		class Args {
			+ Mode [2]string
			+ Szn [2]string
			+ Lg [2]string
			+ Env [2]string
			+ Logf [2]string
			+ CC [2]string
			+ SetEnv() *sql.DB, error
			+ SetLogger() *logd.Logger, error
			+ SetupDailyETL() string, error
			+ SetupBuildETL() string, error
			+ CustomBothLgETL() string, error
			+ CustomLgETL() string, error
		}
	}
	package benchmark {
	}
	package email {
		class email_funcs {
			+ EmailLog() error 
		}
	}
	package main {
		class main_funcs {
			+ main() 
		}
	}
}
package etl {
	package etl {
		class etl_funcs {
			+ RunNightlyETL() error 
			+ RunSeasonETL() error 
		}
		class Conf {
			+ L logd.Logger
			+ DB *sql.DB
			+ RowCnt int64
			+ Errs []string
		}
	}
	package etlcc {
		class etlcc_funcs {
			+ MakeConcurETL() *ConcurETL 
			+ CCSeasonsETL() string, error
		}
		class ConcurETL {
			+ Cnf *Conf
			+ CCBuildModeETL() string, error
		}
	}
	package gamelog {
		class gamelog_funcs {
			+ GameLogReqNew() GetReq 
			+ GameLogReq() GetReq 
			+ GLogParams() LgTbls 
			+ LgSznGlogs() error 
			+ GetManyGLogs() error 
			+ GLogSeasonETL() error 
			+ GLogDailyETL() error 
			+ GameLogETL() error 
		}
	}
	package players {
		class players_funcs {
			+ PlayerReq() GetReq 
			+ PlayersParams() LgTbls 
			+ SznPlayersETL() error 
			+ CrntPlayersETL() error 
		}
	}
	package insert {
		class insert_funcs {
			+ MakeInsert() InsertStmnt 
			+ ValsFromSet() []any 
		}
		class InsertStmnt {
			+ Tbl string
			+ PrimKey string
			+ Cols []string
			+ Vals []any
			+ Rows [][]any
			+ Chunks [][][]any
			+ FlattenVals() 
			+ ChunkVals() 
			+ InsertFast() error 
			+ Insert() error 
			+ BuildStmnt() string 
			+ addCols() 
			+ addChunkParams() 
		}
		class Table {
			+ Name string
			+ PrimKey string
			+ PlTm string
		}
		class LgTbls {
			+ lgs []string
			+ tbls []Table
		}
	}
	package req {
		class GetReq {
			+ Host string
			+ Endpoint string
			+ Params []Pair
			+ Headers []Pair
			+ MakeFulLURL() string 
			+ endptURL() string 
			+ makeQryStr() string 
			+ addHdrs() 
		}
		class Pair {
			+ Key string
			+ Val string
		}
	}
	package reqcc {
	}
	package resp {
		class resp_funcs {
			+ RequestResp() Resp, error
			+ RespFromClient() []byte, error
			+ ProcessResp() 
			+ UnmarshalInto() Resp, error
		}
		class Resp {
			+ Resource string
			+ Parameters any
			+ ResultSets []ResultSet
		}
		class ResultSet {
			+ Name string
			+ Headers []string
			+ RowSet [][]any
		}
	}
	package schedule {
		class schedule_funcs {
			+ SchedReq() GetReq 
			+ RequestSchedule() error 
		}
		class RespSched {
			+ Dates GameDates
		}
		class GameDates {
			+ GmDates []GameDate
		}
		class GameDate {
			+ Date string
		}
	}
	package seasons {
		class seasons_funcs {
			+ Yesterday() string 
			+ SznBSlice() []string, error
			+ SznSlice() []string, error
			+ CurrentSzns() []string 
			+ GetSeasons() SeasonLeague 
		}
		class SeasonLeague {
			+ Szn string
			+ WSzn string
		}
	}
	package base {
	}
}
main <-- etl

@enduml